version: "3.8"

services:
  hub-servis-backend:
    build: ../HubServis-API/
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - "../HubServis-API/:/app/backend"
      - "/app/node_modules"